export default function template(body) {
    return `<!DOCTYPE html>
  <html lang="en">
  
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Felix Antonio Cabello Garmendia">
    <meta name="googlebot" content="index">
    <meta name="googlebot" content="follow">
    <meta name="slurp" content="index">
    <meta name="slurp" content="follow">
    <meta name="robots">
    <meta name="user-scalable" content="no">
    <!-- animate.css -->
    <link rel="stylesheet" href="/css/animate.min.css"
      type="text/css" />
    <!-- Preload CSS -->
    <link rel="stylesheet" href="/css/preload.css"/>
    <meta name="description"
      content="This is my portfolio, I'll be getting it better. Each day, each moment I can, because this is going to demonstrate my abilities, this is my way to demonstrate to myself what I'm able to do. Towards the future">
    <meta name="keywords" content="Portfolio">
    <meta name="keywords" content="CVOnline">
    <meta name="keywords" content="USA">
    <meta name="keywords" content="EEUU">
    <meta name="keywords" content="United States">
    <meta name="keywords" content="Venezuela">
    <meta name="keywords" content="Latam">
    <meta name="keywords" content="Latinoamerica">
    <meta name="keywords" content="Fantoniox">
    <meta name="keywords" content="Future">
    <title>elix Antonio Cabello Portfolio/CVonline</title>
    <!-- Josefin Sans Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300&display=swap" rel="stylesheet">
    <!-- Normalize -->
    <link rel="stylesheet" href="/css/normalize.css" type="text/css">
    <!-- Boopstrap -->
    <link href="/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <!-- Common Style -->
    <link rel="stylesheet" href="/css/index.css" type="text/css">
    <!-- Icon link -->
    <link rel="shortcut icon" href="/img/icon.png" type="image/x-icon" />
    <!-- AnimeJS-->
    <script src="/js/anime.min.js"></script>
  
  </head>
  
    <body allow="fullscreen *">
    
      <div class="body" id="body">
        <!-- Contact page -->
        <!-- Main -->
        <!-- Generated by template -->
        <!-- Home page or welcoming page -->
          ${body}
      </div>
      
      <script src="/js/polyfill.bundle.js" type="application/javascript"></script>
      <!-- app -->
      <script src="/js/app.bundle.min.js" type="application/javascript"></script>
      <!-- Vendor -->
      <script src="/js/vendor.bundle.min.js" type="application/javascript"></script>
      <!-- Home -->
      <script src="/js/home.js" type="application/javascript"></script>
    </body>
    
    </html>`;
}
